### PR TITLE
Hotfix for Assetto Corsa v1.3

### PR DESCRIPTION
**Pull request by StoneSpb**
1. Added 64-bit support for ctypes as described here: http://www.assettocorsa.net/forum/index.php?threads/shared-memory-for-python-applications-sim_info-py-for-ac-v0-22.11382/page-3#post-556752
2. Fixed an error (caused by recent refactoring) with `self.sector_lookup`.

P.S. Have you managed to take a few screenshots with virtual mirror? :)

### CODE REVIEW

**Comment by jamessanford** [comment]
Thanks!  I'm prepping a DeltaBar 1.30 release now.

I'm planning on using your latest code, but with the delta stripe color being the original colors by default (delta_stripe_color)

**Comment by jamessanford** [comment]
Thanks so much!  I won't merge this pull request, but only because I committed slightly different diffs in 5b2bb759609d00c858c381379bfa3b04f25e21fe and 6ae54d8304906893e29003ae8708db3b2dcae852 (and an oopsie fix in ef83b14b1beda81f53019ac5863a5c52583d7f19)

**Comment by StoneSpb** [comment]
Thanks! Your variant is much cleaner :) Didn't assume that sys path can be set in a separate file and happy now that original sim_info.py wasn't touched :)
Nevertheless, that "hotfix" code helped someone and that's good.

Do you have plans to update screenshot images?

**Comment by jamessanford** [comment]
If I stop being lazy and take some screenshots at different resolutions for you, we can update the screenshots :)

**Pull request closed without merging**
